socio.selectByAttivita= select distinct s from Socio s \
inner join s.abbonementos abb \
inner join abb.attivitas att \
where att.description = :attivita


socio.selectByFilter = select s from Socio s \
left join s.abbonementos abb \
left join abb.attivitas att \
where (:id is null or s.id = :id) \
and (:nome is null or nome like :nome%) \
and (:cognome is null or cognome like :cognome%) \
and (:attivita is null or att.id = :attivita)